export enum WorkObjectType {
  CALL = "Call",
  CAR = "Car",
  DATA = "Data",
  DOCUMENT = "Document",
  EURO = "Euro",
  FOLDER = "Folder",
  GAVEL = "Gavel",
  CONVERSATION = "Conversation",
  MISC = "Misc",
  PERSON = "Person",
  THUMB_UP_DOWN = "Thumb-up-down",
  SECURITY = "Security",
  SYSTEM = "System",
}
